# Utiliza una imagen ligera de Nginx como base
FROM nginx:alpine

# Copia el archivo de configuración personalizado de Nginx al contenedor
COPY nginx.conf /etc/nginx/nginx.conf

# Exponer el puerto 80 para Nginx
EXPOSE 80

# CMD predeterminado de nginx: no es necesario especificarlo si se utilizará el comando predeterminado
