version: '3.8'
services:
  uala-app1:
    build:
      context: .
      dockerfile: Dockerfile-app
    container_name: uala-app1
    environment:
      - SPRING_PROFILES_ACTIVE=production
    networks:
      - backend

  uala-app2:
    build:
      context: .
      dockerfile: Dockerfile-app
    container_name: uala-app2
    environment:
      - SPRING_PROFILES_ACTIVE=production
    networks:
      - backend

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge
